### ISSUE TITLE
Loop attribute stopping ended event firing on audio

### ISSUE THREAD

**Issue by Zeludon** [deansheather/takeb1nzyto.space#8]
The code in `music.js` adds an event listener for the end of the audio stream to change music, but due to the `loop` attribute on `<audio id="audio" autoplay loop style="display: none;" src=""></audio>` this event is never fired, I suggest removing the loop  attribute to allow the music to change, note that it will not change if the music track is specified with `?song=`

**Comment by deansheather** [comment]
Oh okay, no one actually told me I was added as a participant. I'm rewriting the code for takeb1nzyto.space today actually @Zeludon. I'll fix a bunch of things. It'll be great.
